### ISSUE TITLE
[Data] - 코어 데이터 설계

### ISSUE THREAD

**Issue by HIBAR97** [ADA-RLD/MacC-Team3-RLD#4]
## ✅ Todo
- [x] 코어 데이터 설계
- [ ] 공용 데이터 Struct 설계
- [x] 앱 environment 연결
- [ ] Core Data PLUD
