### ISSUE TITLE
[Feat] - ChatGpt API 연결

### ISSUE THREAD

**Issue by whaeundo25** [ADA-RLD/MacC-Team3-RLD#9]
## ✅ TODO
- [ ] ChatGpt API  설정
- [ ] ChatGpt API 연결
- [ ] 각 카테고리에 맞게 프롬프트 설정
